# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib scipy Pillow scikit-image opencv-python pandas lmfit xlrd doxypypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with doctest
      run: |
        cd src
        python -m doctest -o 'NORMALIZE_WHITESPACE' Tif.doctest
        python -m doctest -o 'NORMALIZE_WHITESPACE' nanoIndent.doctest
    - name: Install and run doxygen
      run: |
        sudo apt-get install doxygen
        cd src
        python ../doxygen/buildDoxy.py
        doxygen ../doxygen/Doxyfile
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public